#!/usr/bin/env ruby

require "fake/git"
require "optparse"

# Parse options
$OPTIONS = Hash.new
OptionParser.new do |opts|
  opts.set_banner "Welcome to FakeGit"
  opts.on("--stdin", "Get output from stdin") do
    $OPTIONS[:stdin] = true
  end

  opts.on("-w", "Introduce writeable") do
    $OPTIONS[:stdin] = true
  end

  opts.on("-s", "get size for catfile") { $OPTIONS[:cat_file_size] = true }
  opts.on("-p", "print for catfile") { $OPTIONS[:cat_file_print] = true }
  opts.on("-t", "type for catfile") { $OPTIONS[:cat_file_type] = true }

  opts.on("--add", "silence option for update-index") { $OPTIONS[:update_index_add] = true }
  opts.on("--cache-info", "get file info for object") { |v| $OPTIONS[:update_index_cache_info] = v }

  opts.on("-m", "--message [message]", "commit message") { |msg| $OPTIONS[:commit_message] = msg }
end.parse!

# begin exe

cmd, _ = ARGV
if cmd.nil? || !$OPTIONS[:stdin]
  Fake::Git.call(ARGV)
  return
end

# with stdin
while input = STDIN.gets
  input.each_line do |line|
    begin
      full_cmd = [cmd, line].flatten

      Fake::Git.call( full_cmd )
    rescue Errno::EPIPE
      exit(74)
    end
  end
end
